// lib/data.ts — Shared NaturoAmrit data

  export const juices = [
    {
      id: "liver-detox",
      category: "liver",
      emoji: "🫀",
      // add images in public/juices and update paths here
      image: "/juices/liver-detox.png",
      tag: "Liver Support Juice",
      name: "NaturoAmrit Liver Ras",
      tagline: "Supports liver detox & healthy digestion",
      composition: [
        { name: "Giloy juice", qty: "15 ml" },
        { name: "Amla juice", qty: "50 ml" },
        { name: "Beetroot juice", qty: "80 ml" },
        { name: "Methi leaves extract", qty: "15 ml" },
        { name: "Turmeric", qty: "3 ml" },
        { name: "Water", qty: "balance" },
      ],
      bestFor: ["Fatty liver", "Digestion", "Detox"],
      avoid: ["Liver disease patients under treatment", "Pregnant women", "Autoimmune conditions"],
      price: 50,
      volume: "200 ml",
      bg: "bg-amber-50",
      border: "border-amber-200",
      badge: "bg-amber-100 text-amber-800",
      accent: "text-amber-600",
      btnBg: "bg-amber-500 hover:bg-amber-600",
    },
    {
      id: "heart-health",
      category: "heart",
      emoji: "❤️",
      image: "/juices/heart-health.png",
      tag: "Heart Health Juice",
      name: "NaturoAmrit Heart Ras",
      tagline: "Supports healthy cholesterol & circulation",
      composition: [
        { name: "Arjun chaal decoction", qty: "40 ml" },
        { name: "Beetroot juice", qty: "80 ml" },
        { name: "Carrot juice", qty: "80 ml" },
        { name: "Amla juice", qty: "30 ml" },
      ],
      bestFor: ["High cholesterol", "BP support", "Heart health"],
      avoid: ["Low BP patients", "Heart patients on medication"],
      price: 50,
      volume: "200 ml",
      bg: "bg-red-50",
      border: "border-red-200",
      badge: "bg-red-100 text-red-800",
      accent: "text-red-600",
      btnBg: "bg-red-500 hover:bg-red-600",
    },
    {
      id: "sugar-control",
      category: "sugar",
      emoji: "🌿",
      image: "/juices/sugar-control.png",
      tag: "Sugar Balance Juice",
      name: "NaturoAmrit Sugar Balance Ras",
      tagline: "Helps maintain healthy blood sugar levels",
      composition: [
        { name: "Karela juice", qty: "80 ml" },
        { name: "Amla juice", qty: "40 ml" },
        { name: "Methi water", qty: "30 ml" },
        { name: "Jamun leaf extract", qty: "10 ml" },
        { name: "Neem extract", qty: "5 ml" },
        { name: "Water", qty: "balance" },
      ],
      bestFor: ["Pre-diabetes", "High sugar levels"],
      avoid: ["Low sugar tendency", "Strong diabetes medication", "Pregnant women"],
      price: 50,
      volume: "200 ml",
      bg: "bg-green-50",
      border: "border-green-200",
      badge: "bg-green-100 text-green-800",
      accent: "text-green-700",
      btnBg: "bg-green-600 hover:bg-green-700",
    },
    {
      id: "kidney-detox",
      category: "kidney",
      emoji: "💧",
      image: "/juices/kidney-detox.png",
      tag: "Kidney Support Juice",
      name: "NaturoAmrit Kidney Ras",
      tagline: "Supports hydration & kidney function",
      composition: [
        { name: "Lauki juice", qty: "150 ml" },
        { name: "Dhaniya juice", qty: "40 ml" },
        { name: "Amla juice", qty: "30 ml" },
        { name: "Lemon", qty: "5 ml" },
      ],
      bestFor: ["Water retention", "Mild kidney support"],
      avoid: ["Advanced kidney disease", "Dialysis patients"],
      price: 50,
      volume: "200 ml",
      bg: "bg-sky-50",
      border: "border-sky-200",
      badge: "bg-sky-100 text-sky-800",
      accent: "text-sky-600",
      btnBg: "bg-sky-500 hover:bg-sky-600",
    },
    {
      id: "weight-loss",
      category: "weight",
      emoji: "🔥",
      image: "/juices/weight-loss.png",
      tag: "Weight Management Juice",
      name: "NaturoAmrit Weight Ras",
      tagline: "Supports metabolism & healthy weight management",
      composition: [
        { name: "Lauki juice", qty: "150 ml" },
        { name: "Methi water", qty: "20 ml" },
        { name: "Dhaniya juice", qty: "20 ml" },
        { name: "Ginger", qty: "3 ml" },
        { name: "Lemon", qty: "5 ml" },
      ],
      bestFor: ["Weight loss", "Belly fat", "Bloating"],
      avoid: ["Underweight individuals", "Gastric ulcer patients"],
      price: 50,
      volume: "200 ml",
      bg: "bg-orange-50",
      border: "border-orange-200",
      badge: "bg-orange-100 text-orange-800",
      accent: "text-orange-600",
      btnBg: "bg-orange-500 hover:bg-orange-600",
    },
    {
      id: "blood-purifier",
      category: "skin",
      emoji: "✨",
      image: "/juices/blood-purifier.png",
      tag: "Skin Glow Juice",
      name: "NaturoAmrit Skin Glow Ras",
      tagline: "Supports clear skin & natural glow",
      composition: [
        { name: "Neem extract", qty: "5 ml" },
        { name: "Giloy juice", qty: "15 ml" },
        { name: "Amla juice", qty: "50 ml" },
        { name: "Tulsi extract", qty: "5 ml" },
        { name: "Water", qty: "balance" },
      ],
      bestFor: ["Body detox", "Immunity support"],
      avoid: ["Pregnant women", "Low BP individuals", "Long-term continuous use"],
      price: 50,
      volume: "200 ml",
      bg: "bg-purple-50",
      border: "border-purple-200",
      badge: "bg-purple-100 text-purple-800",
      accent: "text-purple-600",
      btnBg: "bg-purple-500 hover:bg-purple-600",
    },
    {
      id: "immunity-booster",
      category: "immunity",
      emoji: "🛡️",
      image: "/juices/immunity-booster.png",
      tag: "Immunity Booster Juice",
      name: "NaturoAmrit Immunity Ras",
      tagline: "Supports natural immunity & daily wellness",
      composition: [
        { name: "Amla juice", qty: "80 ml" },
        { name: "Giloy", qty: "10 ml" },
        { name: "Ginger", qty: "3 ml" },
        { name: "Turmeric", qty: "3 ml" },
        { name: "Honey (optional)", qty: "5 ml" },
        { name: "Water", qty: "balance" },
      ],
      bestFor: ["Frequent cold/cough", "Low immunity"],
      avoid: ["Autoimmune disease patients", "Allergy-prone individuals"],
      price: 50,
      volume: "200 ml",
      bg: "bg-emerald-50",
      border: "border-emerald-200",
      badge: "bg-emerald-100 text-emerald-800",
      accent: "text-emerald-700",
      btnBg: "bg-emerald-600 hover:bg-emerald-700",
    },
    {
      id: "all in one",
      category: "all-in-one",
      emoji: "🛡️",
      image: "/juices/all-in-one.png",
      tag: "All-in-One Wellness Juice",
      name: "NaturoAmrit All-in-One Ras",
      tagline: "Complete Health Plan - 7 Days, 7 Juices, 7 Benefits",
      composition: [
        { name: "Liver support juice", qty: "Monday" },
        { name: "Heart Health juice", qty: "Tuesday" },
        { name: "Immunity Booster juice", qty: "Wednesday" },
        { name: "Sugar Balance juice", qty: "Thursday" },
        { name: "Kidney support juice", qty: "Friday" },
        { name: "Weight Management juice", qty: "Saturday" },
        { name: "Skin Glow juice", qty: "Sunday" },
      ],
      bestFor: ["Overall wellness", "Detox", "Health maintenance"],
      avoid: ["Autoimmune disease patients", "Allergy-prone individuals"],
      price: 50,
      volume: "200 ml",
      bg: "bg-emerald-50",
      border: "border-emerald-200",
      badge: "bg-emerald-100 text-emerald-800",
      accent: "text-emerald-700",
      btnBg: "bg-emerald-600 hover:bg-emerald-700",
    },
  ];

export const plans = [
  {
    id: "starter",
    days: 7,
    label: "Starter",
    price: 350,
    perDay: 50,
    desc: "Perfect for first-timers wanting to experience Ayurvedic healing.",
    features: ["1 juice per day", "Fresh preparation", "Usage guidance included", "WhatsApp support"],
    popular: false,
  },
  {
    id: "wellness",
    days: 15,
    label: "Wellness",
    price: 750,
    perDay: 50,
    desc: "Our most popular plan for noticeable, lasting health improvement.",
    features: ["1 juice per day", "Fresh preparation", "Usage guidance included", "WhatsApp support", "Progress check-in"],
    popular: true,
  },
  {
    id: "transform",
    days: 30,
    label: "Transform",
    price: 1500,
    perDay: 50,
    desc: "The complete Ayurvedic therapy cycle for deep, lasting results.",
    features: ["1 juice per day", "Fresh preparation", "Usage guidance included", "WhatsApp support", "Progress check-in", "Free consultation"],
    popular: false,
  },
];

export const testimonials = [
  {
    id: "priya-sharma",
    name: "Priya Sharma",
    role: "Marketing Manager, Gurgaon",
    text: "My blood sugar levels improved in 15 days. The freshness and purity are unmatched. This is the wellness investment every working professional should make.",
    result: "Blood sugar levels stable",
    juiceUsed: "Sugar Control",
  },
  {
    id: "rahul-verma",
    name: "Rahul Verma",
    role: "Startup Founder, Delhi",
    text: "Replaced my expensive energy drinks with NaturoAmrit. More focused, better digestion, zero guilt. The Immunity Booster is my go-to before important meetings.",
    result: "Enhanced energy & focus",
    juiceUsed: "Immunity Booster",
  },
  {
    id: "anjali-patel",
    name: "Anjali Patel",
    role: "Fitness Enthusiast, Gurgaon",
    text: "Lost 3 kg in a month without feeling deprived. The juices taste fresh and natural. My skin has also gotten clearer since I started the Weight Loss plan.",
    result: "3 kg weight loss",
    juiceUsed: "Weight Loss",
  },
  {
    id: "vikram-singh",
    name: "Vikram Singh",
    role: "Corporate Executive, NCR",
    text: "My cholesterol dropped from 220 to 185 in 6 weeks. The Heart Health juice is my daily ritual. Worth every rupee.",
    result: "Cholesterol reduced by 35 points",
    juiceUsed: "Heart Health",
  },
];

export const juiceCategories = [
  { id: "all", label: "All Juices", icon: "🎯" },
  { id: "liver", label: "Liver Support", icon: "🫀" },
  { id: "heart", label: "Heart Health", icon: "🫀" },
  { id: "sugar", label: "Blood Sugar", icon: "🩸" },
  { id: "kidney", label: "Kidney Health", icon: "💧" },
  { id: "weight", label: "Weight Loss", icon: "🔥" },
  { id: "skin", label: "Skin & Glow", icon: "✨" },
  { id: "immunity", label: "Immunity", icon: "🛡️" },
  { id: "all-in-one", label: "All-in-One", icon: "🧠" }, ,
];

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/juices", label: "Juices" },
  { href: "/plans", label: "Plans" },
  { href: "/review", label: "Reviews" },
  { href: "/about", label: "About" },

];