// lib/data.ts — Shared MediXpert data

export const juices = [
  {
    id: "liver-detox",
    emoji: "🫀",
    // add images in public/juices and update paths here
    image: "/juices/liver-detox.png",
    tag: "Liver Cleanse Juice",
    name: "Liver Detox",
    tagline: "Flush. Cleanse. Restore.",
    composition: [
      { name: "Giloy juice", qty: "15 ml" },
      { name: "Amla juice", qty: "50 ml" },
      { name: "Beetroot juice", qty: "80 ml" },
      { name: "Methi leaves extract", qty: "15 ml" },
      { name: "Turmeric", qty: "3 ml" },
      { name: "Water", qty: "balance" },
    ],
    bestFor: ["Fatty liver", "Digestion", "Detox"],
    avoid: ["Liver disease patients under treatment", "Pregnant women", "Autoimmune conditions"],
    price: 50,
    volume: "200 ml",
    bg: "bg-amber-50",
    border: "border-amber-200",
    badge: "bg-amber-100 text-amber-800",
    accent: "text-amber-600",
    btnBg: "bg-amber-500 hover:bg-amber-600",
  },
  {
    id: "heart-health",
    emoji: "❤️",
    image: "/juices/heart-health.png",
    tag: "Heart Booster Juice",
    name: "Heart Health",
    tagline: "Strengthen. Circulate. Thrive.",
    composition: [
      { name: "Arjun chaal decoction", qty: "40 ml" },
      { name: "Beetroot juice", qty: "80 ml" },
      { name: "Carrot juice", qty: "80 ml" },
      { name: "Amla juice", qty: "30 ml" },
    ],
    bestFor: ["High cholesterol", "BP support", "Heart health"],
    avoid: ["Low BP patients", "Heart patients on medication"],
    price: 50,
    volume: "200 ml",
    bg: "bg-red-50",
    border: "border-red-200",
    badge: "bg-red-100 text-red-800",
    accent: "text-red-600",
    btnBg: "bg-red-500 hover:bg-red-600",
  },
  {
    id: "sugar-control",
    emoji: "🌿",
    image: "/juices/sugar-control.png",
    tag: "Sugar Control Juice",
    name: "Sugar Control",
    tagline: "Balance. Regulate. Energise.",
    composition: [
      { name: "Karela juice", qty: "80 ml" },
      { name: "Amla juice", qty: "40 ml" },
      { name: "Methi water", qty: "30 ml" },
      { name: "Jamun leaf extract", qty: "10 ml" },
      { name: "Neem extract", qty: "5 ml" },
      { name: "Water", qty: "balance" },
    ],
    bestFor: ["Pre-diabetes", "High sugar levels"],
    avoid: ["Low sugar tendency", "Strong diabetes medication", "Pregnant women"],
    price: 50,
    volume: "200 ml",
    bg: "bg-green-50",
    border: "border-green-200",
    badge: "bg-green-100 text-green-800",
    accent: "text-green-700",
    btnBg: "bg-green-600 hover:bg-green-700",
  },
  {
    id: "kidney-detox",
    emoji: "💧",
    image: "/juices/kidney-detox.png",
    tag: "Kidney Cleanse Juice",
    name: "Kidney Detox",
    tagline: "Hydrate. Purify. Renew.",
    composition: [
      { name: "Lauki juice", qty: "150 ml" },
      { name: "Dhaniya juice", qty: "40 ml" },
      { name: "Amla juice", qty: "30 ml" },
      { name: "Lemon", qty: "5 ml" },
    ],
    bestFor: ["Water retention", "Mild kidney support", "Summer hydration"],
    avoid: ["Advanced kidney disease", "Dialysis patients"],
    price: 50,
    volume: "200 ml",
    bg: "bg-sky-50",
    border: "border-sky-200",
    badge: "bg-sky-100 text-sky-800",
    accent: "text-sky-600",
    btnBg: "bg-sky-500 hover:bg-sky-600",
  },
  {
    id: "weight-loss",
    emoji: "🔥",
    image: "/juices/weight-loss.png",
    tag: "Fat Cutter Drink",
    name: "Weight Loss",
    tagline: "Cut. Burn. Transform.",
    composition: [
      { name: "Lauki juice", qty: "150 ml" },
      { name: "Methi water", qty: "20 ml" },
      { name: "Dhaniya juice", qty: "20 ml" },
      { name: "Ginger", qty: "3 ml" },
      { name: "Lemon", qty: "5 ml" },
    ],
    bestFor: ["Weight loss", "Belly fat", "Bloating"],
    avoid: ["Underweight individuals", "Gastric ulcer patients"],
    price: 50,
    volume: "200 ml",
    bg: "bg-orange-50",
    border: "border-orange-200",
    badge: "bg-orange-100 text-orange-800",
    accent: "text-orange-600",
    btnBg: "bg-orange-500 hover:bg-orange-600",
  },
  {
    id: "blood-purifier",
    emoji: "✨",
    image: "/juices/blood-purifier.png",
    tag: "Skin Glow Detox",
    name: "Blood Purifier",
    tagline: "Purify. Glow. Radiate.",
    composition: [
      { name: "Neem extract", qty: "5 ml" },
      { name: "Giloy juice", qty: "15 ml" },
      { name: "Amla juice", qty: "50 ml" },
      { name: "Tulsi extract", qty: "5 ml" },
      { name: "Water", qty: "balance" },
    ],
    bestFor: ["Acne / skin issues", "Body detox", "Immunity support"],
    avoid: ["Pregnant women", "Low BP individuals", "Long-term continuous use"],
    price: 50,
    volume: "200 ml",
    bg: "bg-purple-50",
    border: "border-purple-200",
    badge: "bg-purple-100 text-purple-800",
    accent: "text-purple-600",
    btnBg: "bg-purple-500 hover:bg-purple-600",
  },
  {
    id: "immunity-booster",
    emoji: "🛡️",
    image: "/juices/immunity-booster.png",
    tag: "Immunity Shot",
    name: "Immunity Booster",
    tagline: "Defend. Protect. Recover.",
    composition: [
      { name: "Amla juice", qty: "80 ml" },
      { name: "Giloy", qty: "10 ml" },
      { name: "Ginger", qty: "3 ml" },
      { name: "Turmeric", qty: "3 ml" },
      { name: "Honey (optional)", qty: "5 ml" },
      { name: "Water", qty: "balance" },
    ],
    bestFor: ["Frequent cold/cough", "Low immunity", "Seasonal protection"],
    avoid: ["Autoimmune disease patients", "Allergy-prone individuals"],
    price: 50,
    volume: "200 ml",
    bg: "bg-emerald-50",
    border: "border-emerald-200",
    badge: "bg-emerald-100 text-emerald-800",
    accent: "text-emerald-700",
    btnBg: "bg-emerald-600 hover:bg-emerald-700",
  },
];

export const plans = [
  {
    id: "starter",
    days: 7,
    label: "Starter",
    price: 350,
    perDay: 50,
    desc: "Perfect for first-timers wanting to experience Ayurvedic healing.",
    features: ["1 juice per day", "Fresh preparation", "Usage guidance included", "WhatsApp support"],
    popular: false,
  },
  {
    id: "wellness",
    days: 15,
    label: "Wellness",
    price: 750,
    perDay: 50,
    desc: "Our most popular plan for noticeable, lasting health improvement.",
    features: ["1 juice per day", "Fresh preparation", "Usage guidance included", "WhatsApp support", "Progress check-in"],
    popular: true,
  },
  {
    id: "transform",
    days: 30,
    label: "Transform",
    price: 1500,
    perDay: 50,
    desc: "The complete Ayurvedic therapy cycle for deep, lasting results.",
    features: ["1 juice per day", "Fresh preparation", "Usage guidance included", "WhatsApp support", "Progress check-in", "Free consultation"],
    popular: false,
  },
];

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/juices", label: "Juices" },
  { href: "/plans", label: "Plans" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
];